import type { Metadata } from 'next'
import './globals.css'
import { cormorantGaramond } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja'>
      <body className={`${cormorantGaramond.variable} font-cormorant-garamond antialiased`}>
        {children}
      </body>
    </html>
  )
}
